# Generated by Django 3.1.1 on 2020-09-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('publicacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.publicacao')),
                ('local', models.CharField(max_length=128)),
                ('categoria', models.CharField(choices=[('estagio', 'Estágio'), ('clt', 'CLT'), ('pj', 'PJ'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado'), ('evento', 'Evento'), ('freelancer', 'Freelancer')], max_length=32)),
                ('data_expiracao', models.DateField(verbose_name='Data Expiração')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
            },
            bases=('core.publicacao',),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('publico', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.aluno')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.professor')),
            ],
            options={
                'verbose_name': 'Avaliacão',
                'verbose_name_plural': 'Avaliacões',
            },
        ),
    ]
